services:

# ... Contenido del resto del stack.

# Integración de dbguardian con el stack
  yourapp-dbguardian:
    image: vindihub/dbguar-docker:pre
    container_name: yourapp-dbguardian
    volumes:
      - /your/host/path/to/backup/folder:/backups # Vincula la carpeta backups a una carpeta del host.
    networks:
      - yourapp-net
      - uptimekuma-net
    environment:
      - DB_HOST=
      - DB_NAME=
      - DB_USER=
      - DB_PASSWORD= # Se usa para todas las bases de datos
      - DB_TYPE=mysql # mysql, postgre, mariadb
      - UPTIME_KUMA_PUSH_URL=http://UPTIMEKUMA-URL-OR-IP:3001/api/push/YOUR_TOKEN_HERE
    command: ["/bin/bash", "-c", "while true; do /usr/local/bin/backup.sh && sleep 86400; done"]

networks:
  yourapp-net:
  uptimekuma-net:
    external: true